name: Manual Push NginxInc Image to DockerHub

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_TOKEN }}
      - name: Build and Push image to docker Hub
        env:
          TAG: 2.3.0
          REPO: signalsciences/sigsci-nginxinc-ingress-controller
        run: |
          docker buildx create --name build_multiarch --use
          docker buildx build --platform linux/amd64,linux/arm64 --build-arg  NGINX_INGRESS_VERSION=v${TAG} --tag ${REPO}:${TAG} --tag ${REPO}:latest --push .