name: Manual Push NginxInc Image to DockerHub

on:
  workflow_dispatch:

env:
  LATEST_TAG: signalsciences/sigsci-nginxinc-ingress-controller:latest
  VERSION_TAG: signalsciences/sigsci-nginxinc-ingress-controller:2.3.0
  UPSTREAM_NGINX_INGRESS_VERSION: 2.3.0
  DISTRIBUTION: alpine

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NGINX_INGRESS_VERSION=${{ env.UPSTREAM_NGINX_INGRESS_VERSION }}
            CONTAINER_BASE=${{ env.DISTRIBUTION }}
          context: .
          file: Dockerbuild.nginxinc
          push: true
          tags: ${{ env.LATEST_TAG }}, ${{ env.VERSION_TAG }}