name: Manual Push NginxInc Image to DockerHub

on:
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE: signalsciences/sigsci-nginxinc-ingress-controller
  DISTRIBUTION: alpine
  UPSTREAM_NGINX_INGRESS_VERSION: 2.3.0

jobs:
  buildpush_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
             
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile.nginxinc
          build-args: |
            NGINX_INGRESS_VERSION=${{ env.UPSTREAM_NGINX_INGRESS_VERSION }}
            CONTAINER_BASE=${{ env.DISTRIBUTION }}
          push: true
          tags: >-
            ${{ env.DOCKERHUB_IMAGE }}:${{ env.UPSTREAM_NGINX_INGRESS_VERSION }},${{ env.DOCKERHUB_IMAGE}}:latest,
 
      - name: Echo output
        run: >-
          echo "::set-output
          name=image::${{ env.DOCKERHUB_IMAGE}}:latest,${{ env.DOCKERHUB_IMAGE }}:${{ env.UPSTREAM_NGINX_INGRESS_VERSION }}"